version: '3'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - 9090:9090
    volumes:
      - ${DATAPATH}:/etc/linkding/data
    env_file:
      - .env
    restart: unless-stopped
