version: '3'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - ${PORT}:9090
    volumes:
      - ${DATAPATH}:/etc/linkding/data
    restart: unless-stopped
