version: '3.5'
services:
  registry:
    container_name: registry
    network_mode: "bridge"
    image:registry: latest
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: ${REALMNAME}
    volumes:
      - ${DATAPATH}:/var/lib/registry
      - ${AUTHPATH}:/auth
    ports:
      - ${PORT}:5000
    restart: unless-stopped
