version: '3.4'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - YUBICO_CLIENT_ID=${YUBICO_CLIENT_ID}
      - YUBICO_SECRET_KEY=${YUBICO_SECRET_KEY}
      - DOMAIN=${DOMAIN}
      - LOGIN_RATELIMIT_MAX_BURST=${LOGIN_RATELIMIT_MAX_BURST}
      - LOGIN_RATELIMIT_SECONDS=${LOGIN_RATELIMIT_SECONDS}
      - ADMIN_RATELIMIT_MAX_BURST=${ADMIN_RATELIMIT_MAX_BURST}
      - ADMIN_RATELIMIT_SECONDS=${ADMIN_RATELIMIT_SECONDS}
    restart: always
    volumes:
      - ${DATA_DIR}:/data
    ports:
      - ${PORT}:80
    dns:
      - ${DNS}
    env_file:
      - .env      
volumes: 
${DATA_DIR}:
