version: "3.7"

services:
  time_machine:
    environment:
     - SMB_USER=${USER}
     - SMB_PASSWORD=${PASSWORD}
    image: msjpq/time-machine
    container_name: time-machine
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DATAPATH}:/share
