services:
  windows:
    image: dockurr/windows
    container_name: windows_${windowsversion}
    environment:
      VERSION: ${windowsversion}
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006 # VNC
      - 3389:3389/tcp # RDP
    stop_grace_period: 2m
