version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - SERVERPORT=${PORT}
      - PEERS=${PEERS}
      - PEERDNS=${PEER_DNS}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET} 
      - ALLOWEDIPS=${ALLOWED_IP} 
    volumes:
      - ${DATA_DIR}:/config
      - /lib/modules:/lib/modules
    ports:
      - ${UDPPORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    dns:
      - ${DNS}
volumes:
  ${DATA_DIR}:
